FeatureHashing
==============

Implement feature hashing with R

## Demo

### Hashed Matrix

```{r}
library(FeatureHashing)
# create a "CSRMatrix"
m1 <- hashed.model.matrix(~ ., data = CO2, hash_size = 2^4)
# the structure is similar to "Matrix::dgCMatrix"
library(Matrix)
m2 <- sparse.model.matrix(~ ., data = CO2, transpose = TRUE)
str(m1)
str(m2)
# You can convert "CSRMatrix" to "Matrix::dgCMatrix" if you want ot use advanced API
m3 <- as(m1, "dgCMatrix")
# As you can see, the hashing trick maps the feature to the space {1, 2, ..., 2^4}
dim(m1)
# The hashing algorithm is crc32 https://en.wikipedia.org/wiki/Cyclic_redundancy_check
FeatureHashing:::hash_without_intercept(letters)
# Note that the string "(Intercept)" will always be map to 1
# The hashed.model.matrix hashes the rownames generated by sparse.model.matrix
# So far, "CSRMatrix" only supports matrix-vector multiplication
v <- rnorm(2^4)
all.equal(v %*% m1, as.vector(v %*% m3))
# However, the computation speed of "CSRMatrix" should be faster
library(rbenchmark)
benchmark(v %*% m1, v %*% m3)
```

### Tag Feature

```{r}
library(FeatureHashing)
# I also implemented some function to handle tag features
data1 <- data.frame(a = c("1,2,3", "2,3,3", "1,3", "3"), type = c("a", "b", "a", "a"), stringsAsFactors = FALSE)
# The column a is a tag feature whose seperator is ","
# To generate the corresponding model matrix, there are two helper functions: tag and interpret.tag

# tag function expands the tag feature to count or existence
tag(data1$a, split = ",", type = "count")
tag(data1$a, split = ",", type = "existence")

# interpret.tag expands the formula and data.frame
retval <- interpret.tag(~ tag(a, split = ",", type = "count") * type + type * tag(a, split = ",", type = "existence"), data = data1)

# the return list has object(formula) and data
# the object is the expand formula from tag
retval$object
# the data is the data.frame fetch the expanded tag features
retval$data

# We could evaluate the model matrix from the result of interpret.tag
model.matrix(retval$object, data = retval$data)
```
