# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hash_without_intercept_single <- function(src) {
    .Call('FeatureHashing_hash_without_intercept_single', PACKAGE = 'FeatureHashing', src)
}

hash_without_intercept <- function(src) {
    .Call('FeatureHashing_hash_without_intercept', PACKAGE = 'FeatureHashing', src)
}

pair_sort <- function(i, x) {
    invisible(.Call('FeatureHashing_pair_sort', PACKAGE = 'FeatureHashing', i, x))
}

rehash_inplace <- function(m, Rmapping, hash_size) {
    invisible(.Call('FeatureHashing_rehash_inplace', PACKAGE = 'FeatureHashing', m, Rmapping, hash_size))
}

Xv <- function(m, v, retval) {
    .Call('FeatureHashing_Xv', PACKAGE = 'FeatureHashing', m, v, retval)
}

vX <- function(v, m, retval) {
    .Call('FeatureHashing_vX', PACKAGE = 'FeatureHashing', v, m, retval)
}

