# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pair_sort <- function(i, x) {
    invisible(.Call('FeatureHashing_pair_sort', PACKAGE = 'FeatureHashing', i, x))
}

merge <- function(i, x) {
    .Call('FeatureHashing_merge', PACKAGE = 'FeatureHashing', i, x)
}

todgCMatrix <- function(m) {
    .Call('FeatureHashing_todgCMatrix', PACKAGE = 'FeatureHashing', m)
}

tomatrix <- function(m) {
    .Call('FeatureHashing_tomatrix', PACKAGE = 'FeatureHashing', m)
}

.hashed.model.matrix.dataframe <- function(tf, data, hash_size, transpose, retval, keep_hashing_mapping, is_xi, progress) {
    .Call('FeatureHashing_hashed_model_matrix_dataframe', PACKAGE = 'FeatureHashing', tf, data, hash_size, transpose, retval, keep_hashing_mapping, is_xi, progress)
}

#'@export hash.sign
hash.sign <- function(src) {
    .Call('FeatureHashing_xi', PACKAGE = 'FeatureHashing', src)
}

#'@export hashed.value
hashed.value <- function(src) {
    .Call('FeatureHashing_h', PACKAGE = 'FeatureHashing', src)
}

#'@export hashed.interaction.value
hashed.interaction.value <- function(src) {
    .Call('FeatureHashing_h2', PACKAGE = 'FeatureHashing', src)
}

#'@title Convert the integer to raw vector with endian correction
#'@param src integer value.
#'@return raw vector with length 4
#'@export
intToRaw <- function(src) {
    .Call('FeatureHashing_intToRaw', PACKAGE = 'FeatureHashing', src)
}

Xv <- function(m, v, retval) {
    .Call('FeatureHashing_Xv', PACKAGE = 'FeatureHashing', m, v, retval)
}

vX <- function(v, m, retval) {
    .Call('FeatureHashing_vX', PACKAGE = 'FeatureHashing', v, m, retval)
}

split_existence <- function(src, delim) {
    .Call('FeatureHashing_split_existence', PACKAGE = 'FeatureHashing', src, delim)
}

split_count <- function(src, delim) {
    .Call('FeatureHashing_split_count', PACKAGE = 'FeatureHashing', src, delim)
}

.selectColumn <- function(m, index, drop = TRUE, Rretval = NULL) {
    .Call('FeatureHashing_selectColumn', PACKAGE = 'FeatureHashing', m, index, drop, Rretval)
}

.selectRow <- function(m, index, drop = TRUE, Rretval = NULL) {
    .Call('FeatureHashing_selectRow', PACKAGE = 'FeatureHashing', m, index, drop, Rretval)
}

