# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hash_without_intercept <- function(src) {
    .Call('FeatureHashing_hash_without_intercept', PACKAGE = 'FeatureHashing', src)
}

rehash_inplace <- function(m, Rmapping, hash_size) {
    .Call('FeatureHashing_rehash_inplace', PACKAGE = 'FeatureHashing', m, Rmapping, hash_size)
}

